# Build và deploy lên gh-pages branch
name: Build and Deploy to gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # Optional: Setup Node.js nếu cần build process
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Optional: Install và build (uncomment nếu cần)
      # - name: Install dependencies 📦
      #   run: npm ci
      #
      # - name: Build 🔧
      #   run: npm run build

      # Deploy static files lên gh-pages branch
      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
          single-commit: true
          commit-message: 'Deploy from main branch: ${{ github.sha }}'

# Action này sẽ:
# 1. Tạo hoặc cập nhật nhánh gh-pages
# 2. Copy tất cả files từ root directory (.) vào gh-pages
# 3. Clean old files và commit new files
# 4. GitHub Pages settings cần được set để serve từ gh-pages branch
