# GitHub Actions workflow để deploy tự động lên GitHub Pages
name: Deploy to GitHub Pages

# Trigger workflow khi push vào branch main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cho phép thực hiện workflow thủ công
  workflow_dispatch:

# Thiết lập permissions cho GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một deployment chạy cùng lúc
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job để build và deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code từ repository
    - name: Checkout
      uses: actions/checkout@v4
      
    # Setup Node.js (optional, chỉ cần nếu có build process)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # Cài đặt dependencies (nếu cần)
    # - name: Install dependencies
    #   run: npm ci
    
    # Build project (nếu cần)
    # - name: Build
    #   run: npm run build
      
    # Setup GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    # Upload artifacts
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload toàn bộ repository (vì đây là static site)
        path: '.'
        
    # Deploy lên GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
